### ISSUE TITLE
IPlatformOptions Starting Address isn't available

### ISSUE THREAD

**Issue by Scotts-Thoughts** [gamehook-io/gamehook#26]
**Ex.**
File: GameHook.Application/Platform.cs
```
    public class GB_PlatformOptions : IPlatformOptions
    {
        public EndianTypes EndianType { get; } = EndianTypes.LittleEndian;

        public MemoryAddressBlock[] Ranges { get; } = new List<MemoryAddressBlock>()
        {
            new MemoryAddressBlock(0, "ROM Bank 00", 0x0000, 0x3FFF),
            new MemoryAddressBlock(1, "ROM Bank 01", 0x4000, 0x7FFF),
            new MemoryAddressBlock(2, "VRAM", 0x8000, 0x9FFF),
            new MemoryAddressBlock(3, "External RAM (Part 1)", 0xA000, 0xAFFF),
            new MemoryAddressBlock(4, "External RAM (Part 2)", 0xB000, 0xBFFF),
            new MemoryAddressBlock(5, "Work RAM (Part 1)", 0xC000, 0xCFFF),
            new MemoryAddressBlock(6, "Work RAM (Part 2)", 0xD000, 0xDFFF),
            new MemoryAddressBlock(7, "High RAM", 0xFF80, 0xFFFF)
        }.ToArray();
    }
```
Properties that start at the first memory address of each MemoryAddressBlock
(0x0000, 0x4000, 0x8000 etc) cause Gamehook to crash.

**Comment by flamesage** [comment]
This should be fixed in version 2022.7.31.1 -- could you confirm for me?

**Comment by Scotts-Thoughts** [comment]
Fixed for starting addresses. The ending addresses seem to throw an error as well. ex. 0x3FFF, 0xAFFF, 0xFFFF

```
2022-07-31 15:30:00.825 -06:00 [Error] (GameHook.Application.GameHookInstance) An error occured when loading the mapper.
System.AggregateException: One or more errors occurred. (Failed to process propery player.testTestTest3.)
 ---> GameHook.Domain.PropertyProcessException: Failed to process propery player.testTestTest3.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray[T](T[] array, Range range)
   at GameHook.Application.GameHookProperty.Process(IEnumerable`1 driverResult, PreprocessorCache preprocessorCache)
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()
   --- End of inner exception stack trace ---
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at GameHook.Application.GameHookInstance.Read()
   at GameHook.Application.GameHookInstance.Load(IGameHookDriver driver, String mapperId)
2022-07-31 15:30:00.871 -06:00 [Error] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP "PUT" "/mapper" responded 500 in 172.5068 ms
2022-07-31 15:30:17.379 -06:00 [Error] (GameHook.Application.GameHookInstance) An error occured when loading the mapper.
System.ArgumentException: ID was NULL or empty. (Parameter 'filesystemId')
   at GameHook.Application.GameHookMapperFactory.ReadMapper(GameHookInstance instance, IMapperFilesystemProvider provider, String filesystemId)
   at GameHook.Application.GameHookInstance.Load(IGameHookDriver driver, String mapperId)
2022-07-31 15:30:17.381 -06:00 [Error] (Serilog.AspNetCore.RequestLoggingMiddleware) HTTP "PUT" "/mapper" responded 500 in 2.5586 ms
```

**Comment by Scotts-Thoughts** [comment]
Resolved

**Comment by flamesage** [comment]
Just to confirm, this is also fixed now for ending addresses?

**Comment by Scotts-Thoughts** [comment]
Resolved for ending addresses.
