### ISSUE TITLE
GBA DMA Crash

### ISSUE THREAD

**Issue by Scotts-Thoughts** [gamehook-io/gamehook#35]
Gametime properties stop updating after the cartridge has been reset.
Mapper stays loaded for a bit and then crashes. (Other properties do not update during this time)
I believe when the DMA pointers are cleared the crash [occurs]

Here is the Gamehook log from when the error occured.
```
2022-08-23 18:05:41.954 -06:00 [Information] (Program) Starting GameHook version 2022.8.23.1+d42dbfed.
2022-08-23 18:05:42.000 -06:00 [Information] (Program) GameHook is now online. Accessible via: http://localhost:8085
2022-08-23 18:05:42.001 -06:00 [Information] (Program) Navigate to the above URL in order to access the Web UI.
2022-08-23 18:05:45.103 -06:00 [Information] (GameHook.Application.GameHookInstance) Loaded mapper for Pokemon Yellow.
2022-08-23 18:06:03.511 -06:00 [Error] (GameHook.Application.GameHookInstance) An error occured when read looping the mapper.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.ThrowObjectDisposedException()
   at System.Net.Sockets.Socket.SendAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, IPEndPoint endPoint)
   at GameHook.Domain.Drivers.RetroArchUdpPollingDriver.SendPacket(String command, String argument) in D:\a\gamehook\gamehook\src\GameHook.Domain\Drivers\RetroArchUdpPollingDriver.cs:line 124
   at GameHook.Domain.Drivers.RetroArchUdpPollingDriver.ReadMemoryAddress(UInt32 memoryAddress, UInt32 length) in D:\a\gamehook\gamehook\src\GameHook.Domain\Drivers\RetroArchUdpPollingDriver.cs:line 150
   at GameHook.Domain.Drivers.RetroArchUdpPollingDriver.<ReadBytes>b__26_0(MemoryAddressBlock x) in D:\a\gamehook\gamehook\src\GameHook.Domain\Drivers\RetroArchUdpPollingDriver.cs:line 182
   at GameHook.Domain.Drivers.RetroArchUdpPollingDriver.ReadBytes(IEnumerable`1 blocks) in D:\a\gamehook\gamehook\src\GameHook.Domain\Drivers\RetroArchUdpPollingDriver.cs:line 183
   at GameHook.Application.GameHookInstance.Read()
   at GameHook.Application.GameHookInstance.ReadLoop()
2022-08-23 18:06:07.036 -06:00 [Information] (GameHook.Application.GameHookInstance) Loaded mapper for Pokemon Emerald.
2022-08-23 18:06:14.275 -06:00 [Error] (GameHook.Application.GameHookInstance) An error occured when read looping the mapper.
System.AggregateException: One or more errors occurred. (Failed to process propery gameTime.gameTimeHours.) (Failed to process propery gameTime.gameTimeMinutes.) (Failed to process propery gameTime.gameTimeSeconds.) (Failed to process propery gameTime.gameTimeFrames.)
 ---> GameHook.Domain.PropertyProcessException: Failed to process propery gameTime.gameTimeHours.
 ---> System.Exception: Unable to retrieve bytes for property 'gameTime.gameTimeHours' at address 0x0E. Is the address within the drivers' memory address block ranges?
   at GameHook.Application.GameHookProperty.Process(IEnumerable`1 driverResult, PreprocessorCache preprocessorCache)
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()
   --- End of inner exception stack trace ---
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at GameHook.Application.GameHookInstance.Read()
   at GameHook.Application.GameHookInstance.ReadLoop()
 ---> (Inner Exception #1) GameHook.Domain.PropertyProcessException: Failed to process propery gameTime.gameTimeMinutes.
 ---> System.Exception: Unable to retrieve bytes for property 'gameTime.gameTimeMinutes' at address 0x10. Is the address within the drivers' memory address block ranges?
   at GameHook.Application.GameHookProperty.Process(IEnumerable`1 driverResult, PreprocessorCache preprocessorCache)
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()
   --- End of inner exception stack trace ---
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()<---

 ---> (Inner Exception #2) GameHook.Domain.PropertyProcessException: Failed to process propery gameTime.gameTimeSeconds.
 ---> System.Exception: Unable to retrieve bytes for property 'gameTime.gameTimeSeconds' at address 0x11. Is the address within the drivers' memory address block ranges?
   at GameHook.Application.GameHookProperty.Process(IEnumerable`1 driverResult, PreprocessorCache preprocessorCache)
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()
   --- End of inner exception stack trace ---
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()<---

 ---> (Inner Exception #3) GameHook.Domain.PropertyProcessException: Failed to process propery gameTime.gameTimeFrames.
 ---> System.Exception: Unable to retrieve bytes for property 'gameTime.gameTimeFrames' at address 0x12. Is the address within the drivers' memory address block ranges?
   at GameHook.Application.GameHookProperty.Process(IEnumerable`1 driverResult, PreprocessorCache preprocessorCache)
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()
   --- End of inner exception stack trace ---
   at GameHook.Application.GameHookInstance.<>c__DisplayClass41_0.<<Read>b__3>d.MoveNext()<---
```

**Comment by Scotts-Thoughts** [comment]
This is confirmed to be resolved.
